gcp_key_file     = "../advanced-terraform-2823489/serviceAccountKey.json"
gcp_project      = "tf-advanced"
gcp_region       = "us-east1"
gcp_zone         = "us-east1-b"
image            = "ubuntu-os-cloud/ubuntu-1804-bionic-v20220901"
ssh_user         = "test"
ssh_pub_key_file = "id_rsa.pub"