gcp_key_file     = "service_key.json"
gcp_project      = "tf-advanced"
gcp_region       = "us-east1"
gcp_zone         = "us-east1-b"
image            = "ubuntu-os-cloud/ubuntu-1804-bionic-v20220901"
ssh_user         = "theia"
ssh_pub_key_file = "id_rsa.pub"